2021-11-06 12:27:29,338 Downloading artifact
wandb: ERROR Project ash-mohan/exercise_14 does not contain artifact: "raw_data:latest"
Traceback (most recent call last):
  File "/Users/ashwath.mohan/opt/anaconda3/envs/mlflow-484b576132a8d4f86bd93cd736b9c9cac218a14d/lib/python3.9/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/Users/ashwath.mohan/opt/anaconda3/envs/mlflow-484b576132a8d4f86bd93cd736b9c9cac218a14d/lib/python3.9/site-packages/wandb/apis/public.py", line 520, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "/Users/ashwath.mohan/opt/anaconda3/envs/mlflow-484b576132a8d4f86bd93cd736b9c9cac218a14d/lib/python3.9/site-packages/wandb/apis/public.py", line 2583, in __init__
    self._load()
  File "/Users/ashwath.mohan/opt/anaconda3/envs/mlflow-484b576132a8d4f86bd93cd736b9c9cac218a14d/lib/python3.9/site-packages/wandb/apis/public.py", line 3097, in _load
    raise ValueError(
ValueError: Project ash-mohan/exercise_14 does not contain artifact: "raw_data:latest"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ashwath.mohan/Desktop/workspace/classwork/reproducible_workflow/nd0821-c2-build-model-workflow-exercises/lesson-5-final-pipeline-release-and-deploy/genre_classification/preprocess/run.py", line 80, in <module>
    go(args)
  File "/Users/ashwath.mohan/Desktop/workspace/classwork/reproducible_workflow/nd0821-c2-build-model-workflow-exercises/lesson-5-final-pipeline-release-and-deploy/genre_classification/preprocess/run.py", line 19, in go
    artifact = run.use_artifact(args.input_artifact)
  File "/Users/ashwath.mohan/opt/anaconda3/envs/mlflow-484b576132a8d4f86bd93cd736b9c9cac218a14d/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1957, in use_artifact
    artifact = public_api.artifact(type=type, name=name)
  File "/Users/ashwath.mohan/opt/anaconda3/envs/mlflow-484b576132a8d4f86bd93cd736b9c9cac218a14d/lib/python3.9/site-packages/wandb/apis/normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "/Users/ashwath.mohan/opt/anaconda3/envs/mlflow-484b576132a8d4f86bd93cd736b9c9cac218a14d/lib/python3.9/site-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/Users/ashwath.mohan/opt/anaconda3/envs/mlflow-484b576132a8d4f86bd93cd736b9c9cac218a14d/lib/python3.9/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/Users/ashwath.mohan/opt/anaconda3/envs/mlflow-484b576132a8d4f86bd93cd736b9c9cac218a14d/lib/python3.9/site-packages/wandb/apis/public.py", line 520, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "/Users/ashwath.mohan/opt/anaconda3/envs/mlflow-484b576132a8d4f86bd93cd736b9c9cac218a14d/lib/python3.9/site-packages/wandb/apis/public.py", line 2583, in __init__
    self._load()
  File "/Users/ashwath.mohan/opt/anaconda3/envs/mlflow-484b576132a8d4f86bd93cd736b9c9cac218a14d/lib/python3.9/site-packages/wandb/apis/public.py", line 3097, in _load
    raise ValueError(
wandb.errors.error.CommError: Project ash-mohan/exercise_14 does not contain artifact: "raw_data:latest"
